apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 2
  template: 
    metadata:
    labels:
    app: jenkins
  spec:
     containers:
     - name: jenkins
       image: jenkins:latest
       ports:
       - containerPort: 8080
