#filename javamavengit.yml
---
- name: install java, maven and git
  hosts: all
  remote_user: vagrant
  become: yes
 
  tasks:
   - name: copy Java
     copy: 
       src: /tmp/shared/java.tar.gz 
       dest: /opt/java.tar.gz

   - name: Copy Maven
     copy: 
       src: /tmp/shared/maven.tar.gz 
       dest: /opt/maven.tar.gz

   - name: Install java
     unarchive: 
       src: /opt/java.tar.gz
       dest: /opt/
       copy: no

   - name: Install maven
     unarchive:
       src: /opt/maven.tar.gz
       dest: /opt/
       copy: no

   - name: create symlinks
     shell: "{{ item }}"
     with_items:
      - "update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_45/bin/java 100"
      - "update-alternatives --install /usr/bin/javac javac /opt/jdk1.8.0_45/bin/javac 100"
      - "update-alternatives --install /usr/bin/mvn mvn /opt/apache-maven-3.3.9/bin/mvn 100"

   - name: update package manager  
     apt: update_cache=yes

   - name: install git
     apt: name=git state=present
